### ISSUE TITLE
Scrat 的模块加载器可以替换成requirejs吗

### ISSUE THREAD

**Issue by lovefishs** [scrat-team/scrat#12]
支持 AMD 规范的类库（eg：jquery）可以通过手动的方式放入 component_modules 目录吗？就项目改版适合使用 Scart 来构建项目吗，项目里面使用了很多的非模块化组件。

**Comment by atian25** [comment]
@senro 修改 scrat.js 即可, 我们这边都是做移动端的, 所以没考虑过. 欢迎 PR
