### ISSUE TITLE
Scart SEO模式

### ISSUE THREAD

**Issue by Megasu** [scrat-team/scrat#17]
Scrat-team方便的话在 Scrat SEO 模式里的代码写多点中文注释，如server模块下的 js。

例子较少，注释较少，学习起来较吃力。

可以的话，希望能建一个 scrat 交流群。让使用Scrat的同学能相互交流。

@fouber 
@Hinc

**Comment by atian25** [comment]
https://github.com/scrat-team/pagelet-example
