### ISSUE TITLE
scrat适用于angularjs吗？

### ISSUE THREAD

**Issue by chenbeitingting** [scrat-team/scrat#24]
scrat适用于angularjs的集成发布吗？

**Comment by fouber** [comment]
@chenbeitingting 

可以啊，scrat只是负责管理模块化和资源的，在此之上怎么封装组件跟往常都是一样的啊

**Comment by atian25** [comment]
实践经验告诉你, 适用, 但有些规则需要修改.
譬如:
1. 不能直接templateUrl, 需要用 `__inline()` 或 `__uri()`
2. 动态加载需要特殊处理

我之前封装的这个解决方案就是在scrat的基础上自己封装的, 可以参考下

https://github.com/ng-workflow/ngfis
