### ISSUE TITLE
scrat 和 fis 有支持iojs的计划吗

### ISSUE THREAD

**Issue by okoala** [scrat-team/scrat#26]
rt

**Comment by fouber** [comment]
@okoala 

可能要观望一下，nodejs和iojs不是还要合并吗，再看看情况

**Comment by okoala** [comment]
@fouber 
OK，但是还是希望能同时支持啊~~

**Comment by fouber** [comment]
@okoala 

图片压缩是C语言实现的，然后编译成.node扩展，所以要同时兼容iojs成本略高
