### ISSUE TITLE
有webp的方案不~

### ISSUE THREAD

**Issue by okoala** [scrat-team/scrat#27]

**Comment by fouber** [comment]
@okoala 

图片一般属于业务数据，可以在前端做一个lazyload，然后检查支持webp就在加载真实图片数据的时候在url中加上webp相关参数来加载图片

**Comment by okoala** [comment]
@fouber  我这边业务比较简单，希望有个插件，可以把图片转换成webp，也可以集成智图~然后我这边前端判断load哪个类型的图片。

**Comment by fouber** [comment]
@okoala 

目前没有集成转webp的工具

**Comment by okoala** [comment]
@fouber 了解了
