### ISSUE TITLE
模块加载细节的疑问

### ISSUE THREAD

**Issue by chyingp** [scrat-team/scrat#30]
`scrat`的模块主要分为两类：生态模块 + 工程模块，分别对应 component_modules、components目录。对于这里有些疑问：

1、版本：components 生态下的模块是分版本的，比如 jQuery，可能项目同时存在1.9.1、2.0.0。从官方文档来看，引用只需要 require('jquery')，那么，工具是如何确定加载的是哪个版本？

2、重名：假如 生态模块、攻城模块 存在同名的模块，还是以jQuery为例，同时存在 components/jquery、component_modules/jquery，那么，require('jquery') 的时候，引用的是哪个？

**Comment by fouber** [comment]
@chyingp 

1. scrat有一个component.json文件，描述了版本，跟nodejs类似
2. 默认工程模块优先

**Comment by chyingp** [comment]
@fouber thx :)
