### ISSUE TITLE
调整目录结构

### ISSUE THREAD

**Issue by mtyang** [scrat-team/scrat#32]
可以根据自己的喜好调整配置文件目录结果么？

**Comment by fouber** [comment]
@mtyang 

稍微有点困难，因为：

> 解决方案 = 模块化框架 + 开发规范 + 部署规范 + 构建工具

目录规范和其他几个部分有所关联，改起来稍微困难，不过你可以说一下你的具体调整需求，有些不需要配置的

**Comment by mtyang** [comment]
那估计就不能配置了，改的是顶层结构，release后模块也没打包进来，我看了下fis-prue可以在roadmap中配置，一会研究下，谢谢啦。

**Comment by fouber** [comment]
@mtyang 

可以自己追加roadmap.path，个别地方可能要参考一下当前的配置

**Comment by mtyang** [comment]
好的，我看下，谢谢
