### ISSUE TITLE
scrat  使用 handlebars 模板如何定位资源 ？

### ISSUE THREAD

**Issue by gyf19** [scrat-team/scrat#33]
components 目录下有 user.html 、user.handlebars , 这两个文件内容都引用 
img  src="item_6020003.png"   ，  在编译后只有 user.html 文件img url 会被替换成 /h5app/1.0.0/img/item_6020003_2a0a5b6.png ， user.handlebars 没有改变。

**Comment by gyf19** [comment]
重新设置 path , 也不行
fis.config.merge({
    roadmap : {
        path : [
            {
                reg : '**.handlebars',
                isHtmlLike : true,
                release : false,
                isJsLike : true,
            }
        ]
    }
});

**Comment by fouber** [comment]
@gyf19 

* scrat内部已经这样定过handlebars文件了，这里不用这样书写
* scrat定义handlebars文件为一个“类JS文件”，类JS文件会把这个文件当做JS对待
* 被当做js文件对待的文件，资源定位标识是 ``__uri(path)```
* handlebars编译之后不能直接生成这样的标记，所以，只能采取js传值方式：

```handlebars
<!-- user.handlebars -->
<img src="{{ pic }}" />
``` 

```js
// user.js
var tpl = __inline('user.handlebars');
var pic = __uri('item.png'); //在使用handlebars的js文件中定位资源
var html = tpl({ pic: pic });
console.log(html);
```

**Comment by gyf19** [comment]
只能调用  handlebars 模板时候，以传参数方式了。   觉得怪怪的

**Comment by gyf19** [comment]
handlebars 文件 先像html 文件一样做定位资源 ， 再编译成JS。 就完美了

**Comment by fouber** [comment]
@gyf19 

fis有一个资源内嵌关系表：

| <img src="https://cloud.githubusercontent.com/assets/536297/7695968/266a6438-fe2a-11e4-9d29-3ff2d4f55a6b.png"> | HTML | JS | CSS | 图片 |
|:-------------------------:|:--------:|:---:|:-------:|:------:|
| **HTML** | 内容直接嵌入 | script包裹嵌入 | style包裹嵌入 | base64嵌入 |
| **JS** | 内容转字符串嵌入 | 内容直接嵌入 | 内容字符串嵌入 | base64字符串嵌入 |
| **CSS** | - | - | 内容直接嵌入 | base64嵌入 |

可以让handlebars标记为 ``isHtmlLike`` ，这样是可以识别模板中的 ``<img src="path">`` 标识，但是前端性能可能有点损耗：

### 1. 如果handlebars文件标记为isHtmlLike

``user.handlebars`` 这么写：

```html
<img src="item.png"/>
```

``user.js`` 这么写：

```js
// user.js
var tpl = __inline('user.handlebars');
// 这里需要引入完整版的handlebars库，
// 才有compile函数，在运行时编译模板
Handlebars.compile(tpl); 
var html = tpl({});
console.log(html);
```

user.js经fis构建后的结果：
```js
// user.js
var tpl = '<img src="/h5app/1.0.0/img/item_6020003_2a0a5b6.png"/>'; // js嵌入html，参见上表
Handlebars.compile(tpl); 
var html = tpl({});
console.log(html);
```

### 2. 如果handlebars文件标记为isJsLike

``user.handlebars`` 这么写：

```html
<img src="{{ pic }}"/>
```

``user.js`` 这么写：

```js
// user.js
// 这里只需引入运行时handlebars库，
// 无需运行时编译模板，tp直接就是模板函数
var tpl = __inline('user.handlebars');
var pic = __uri('item.png'); //在js文件中定位资源以数据方式传给模板
var html = tpl({ pic: pic });
console.log(html);
```

user.js经fis构建后的结果：
```js
// user.js
var tpl = Handlebars.template( ... ); // 这里将模板文件预编译为模板函数，这是一种js，直接内嵌
var pic = '/h5app/1.0.0/img/item_6020003_2a0a5b6.png'; // 资源定位
var html = tpl({ pic: pic });
console.log(html);
var html = tpl({});
console.log(html);
```

**Comment by gyf19** [comment]
我想这种结合的东西。handlebars文件同时 标记为isHtmlLike  、isJsLike。

user.handlebars 这么写：
<img src="item.png"/>
user.js 这么写：
// user.js
// 这里只需引入运行时handlebars库，
// 无需运行时编译模板，tp直接就是模板函数
var tpl = __inline('user.handlebars');
var html = tpl({ });
console.log(html);

user.js经fis构建后的结果：
// user.js
var tpl = Handlebars.template( ... ); // 这里将模板文件预编译为模板函数，这是一种js，直接内嵌
var html = tpl({});
console.log(html);

最后结果：
<img src="/h5app/1.0.0/img/item_6020003_2a0a5b6.png"/>

**Comment by fouber** [comment]
@gyf19 

我清楚你的想法，但只是应用到了这个场景，对于fis来说，文件分类需要具有一定的唯一性，还关联了其他处理，所以如果只是为了节省这么一点点工作量而破坏fis在语法能力扩展上的一致性，这是更加不合理的

**Comment by gyf19** [comment]
恩    可以理解    你是从fis高度，来思考的。     哈哈    我使用方便来考虑的
我设计  handlebars 调用方式， 有一些出入。

**Comment by gyf19** [comment]
对了     --domains：是否为静态资源添加域名。   在哪里设置域名？

**Comment by gyf19** [comment]
会用了 
fis.config.merge({
    roadmap : {
        //所有静态资源文件都使用 http://s1.example.com 或者 http://s2.example.com 作为域名
        domain : 'http://s1.example.com, http://s2.example.com'
    }
});

**Comment by fouber** [comment]
@gyf19 

构建的时候在fis release命令中加上 -D 参数
