### ISSUE TITLE
关于使用file://加载资源

### ISSUE THREAD

**Issue by myseawp** [scrat-team/scrat#35]
问题如下:

我们使用scrat发布资源，编译后的所有资源都是使用绝对定位，这也是fis资源定位的重要能力

但我们h5资源是放在app本地加载的，使用file://定位资源，但得到的路径变为file:///文件位置，由于这里多了个/，导致资源定位失败

我觉得这个不是bug，更多是我们使用的方式不同，请问对于这样的使用方式，有没有好的解决方案

**Comment by fouber** [comment]
@myseawp 

```js
// 配置资源域名
fis.config.set('roadmap.domain', 'file:/');
// 配置模块加载器的url规则
fis.config.set('framework.urlPattern', 'file://%s');
```

使用以上两个配置，然后scrat release的时候加上 ``-D`` 参数，domain配置就会生效

如果本地开发是web的，构建之后是file的，推荐这样做：

```js
if(process.env.PROD){
    // 配置资源域名
    fis.config.set('roadmap.domain', 'file:/');
    // 配置模块加载器的url规则
    fis.config.set('framework.urlPattern', 'file://%s');
}
```

然后本地开发使用web-server，就执行：

```bash
scrat release
```

而发版的时候执行：

```bash
PROD=1 scrat release -Doud ./output
```

其中：
* ``PROD=1`` 就是设置一个环境变量，这样你在fis-conf.js中写的那个if判断就会命中
* ``-Doud ./output`` 是多个参数的缩写，展开之后就是 ``-D -o -u -d ./output`` 含义是：加域名（roadmap.domain配置生效）、压缩、独立编译缓存（清除编译缓存）、发布到output目录。这里不应使用 ``-p`` 参数进行资源合并，因为开启-p会使得scrat.js加载资源的时候使用combo合并请求，这个在本地app中是没有的

**Comment by myseawp** [comment]
@fouber 
感谢解答这么详细！

我们使用file://+目录地址+index在工程路径来定位入口文件
(例如,加载目录为：fille://android_asset/www/b/1.0.0/index.html)

由于fis资源定位是将所有资源转化为工程的绝对路径，如果index.html引入资源b.css，那么使用scrat编译后的路径为/c/b/1.0.0/b.css
客户端实际转化的路径就变为了fille:///c/b/1.0.0/b.css，导致资源定位失败
主要原因是客户端本地加载资源，没办法像web那样定义根目录(也可能是我没找到合适的方法）

我尝试使用上述方法，将所有资源转化为fill://路径，但实际客户端路径变为：
fille://android_asset/www/b/1.0.0/file://c/b/1.0.0/b.css

但上面的方法给了我启发：
我使用
if(process.env.PROD){
    // 配置资源域名
    fis.config.set('roadmap.domain', '/root');
    // 配置模块加载器的url规则
    fis.config.set('framework.urlPattern', '/root/c/%s');
}

将所有资源加上前缀/root，在客户端拦截所有url，替换‘/root‘为资源的实际路径，目前测试可以定位资源

但总觉得，这样处理不太好，请问有没有更简单的处理办法，目前还能想到的就是客户端本身也开启一个web服务，通过web服务加载资源，但这样又觉得有点臃肿
