### ISSUE TITLE
css样式动态修改问题

### ISSUE THREAD

**Issue by myseawp** [scrat-team/scrat#38]
hi！

最近在使用scrat遇到一个问题，望指教：

比如，由a，b两个模块，对应模块里有与模块同名的css文件

a模块内部 require('b);

动态添加到dom的样式表结构顺序：
<style>b模块的样式表</style>
<style>a模块的样式表</style>

这个时候如果使用livereload 修改a模块的css样式（修改b模块的css样式结果一样），导致dom结构变更为：
<style>a模块的样式表</style>
<style>b模块的样式表</style>

这个时候，如果模块a b有样式的覆盖关系就乱了，a模块内部可能会有要覆写b模块的样式

请问这种情况能不能解决，另：如果手动刷新页面的话，一切正常，先引入依赖模块的样式，再引入自己样式，顺序是正常的，只是在livereload模式下会出现这种情况

**Comment by fouber** [comment]
@myseawp 

不应该出现这样的问题，能不能在github上建立一个项目，复现这个问题，然后我clone下来看一下

**Comment by myseawp** [comment]
好的，稍等

**Comment by myseawp** [comment]
我这里只监控动态加载的样式表结构：

1. 打开页面，css模块依赖正常：
![image](https://cloud.githubusercontent.com/assets/13513205/9730553/e15b1a40-5649-11e5-8c93-43b00a57cde6.png)
2. 多次修改依赖模块样式表(在release -wL模式下)，dom结构变化了
![image](https://cloud.githubusercontent.com/assets/13513205/9730770/5cb6ed12-564b-11e5-9214-bc3f58eff3da.png)


测试代码：

https://github.com/myseawp/testcss.git

**Comment by fouber** [comment]
@myseawp 

确认是一个loader的加载问题，由于我们线下并不会使用cache选项，所以一直没有发现这个问题。明天会修复。

在这个项目中，有一个配置：

```js
...
fis.config.set('framework', {
    cache: true,
    urlPattern: '/c/%s',
    comboPattern: '/co??%s'
});
```

这里的 ``cache: true`` 会让scrat开启localstorage缓存模式，以提升性能，开启之后，scrat会把css构建为js文件并通过script加载，而loader没有控制好这些js的执行时序问题，导致上述bug。

一般这里的配置我们是这样写的：

```js
...
fis.config.set('framework', {
    cache: !!process.env.SCRAT_CACHE,
    urlPattern: '/c/%s',
    comboPattern: '/co??%s'
});
```

然后本地开发时就使用正常的link标签加载css，不会有执行时序问题。如果上线的时候通过这样构建：

```
SCRAT_CACHE=1 scrat release -compd ../dist
```

通过修改环境变量来开启框架的缓存功能。我们一直是这样使用的，所以没有发现这个问题，多谢你的issue

**Comment by fouber** [comment]
@myseawp 已修复，可以下载最新的 [scrat.js](https://github.com/scrat-team/scrat.js) 来解决这个问题

**Comment by myseawp** [comment]
好的 thanks

**Comment by fouber** [comment]
感谢你的issue
