### ISSUE TITLE
Window 安装失败

### ISSUE THREAD

**Issue by yonbin** [scrat-team/scrat#39]
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "scrat" "-g"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

**Comment by fouber** [comment]
@yonbin 

看起来是你的网络问题，请求某些安装包超时，试试使用淘宝的镜像：

```
npm install -g scrat --registry=https://registry.npm.taobao.org
```

**Comment by yonbin** [comment]
淘宝镜像也不行，有其他安装方法吗？

**Comment by yonbin** [comment]
已解决切换到http://cnpmjs.org/下，多试几次，就ok了。
