### ISSUE TITLE
scrat的模块化文件怎么合并

### ISSUE THREAD

**Issue by ahaiboa** [scrat-team/scrat#42]

**Comment by fouber** [comment]
我们采用服务端combo合并请求，并不在线下计算合并

**Comment by fouber** [comment]
我们的框架，scrat.js，在按需加载过程中可以根据资源依赖情况发起一个合并的url，形如：

/co??a.js,b.js,c.js...

**Comment by ahaiboa** [comment]
敢问
1、服务端合并怎么配置？
2、我按scrat里说的设置fis.config.set('framework.cache', true)后直接报错啊。
能不能写一篇关于combo合并请求的原理及实现的文章，现在关于这方面的资料太少了！

**Comment by ahaiboa** [comment]
@fouber 
我开启了framework.combo并设置了framework.urlPattern="/public/c/%s"，但release后运行还是报错
![2015-11-05_170256](https://cloud.githubusercontent.com/assets/13414314/10963983/23c81ea6-83df-11e5-931c-b95dd7c54299.jpg)

**Comment by fouber** [comment]
@ahaiboa 你的服务端支持了动态合并么？

**Comment by ahaiboa** [comment]
@fouber nginx那块应该还没配置，这个是和服务端合并使用的？我以为可以直接依据scrat来做这件事情

**Comment by atian25** [comment]
scrat是在构建期的，combo是在运行期

发自我的 iPhone

**Comment by ahaiboa** [comment]
@atian25 了解了

**Comment by atian25** [comment]
我们是node这层去做combo的, 有express和koa的版本
