### ISSUE TITLE
怎么对项目组件进行测试？

### ISSUE THREAD

**Issue by boxizen** [scrat-team/scrat#43]
问个比较初级的问题，假设我在components目录下添加一菜单组件(menu目录下)，那我要怎么单独测试该组件呢？不知道目前scrat支不支持这样的功能？谢谢～

**Comment by fouber** [comment]
@boxizen 

在views下添加一个页面，只引用这个一个组件，然后再引入qunit，进行测试

**Comment by boxizen** [comment]
好的，非常感谢
