### ISSUE TITLE
scrat现在适用于vue.js吗

### ISSUE THREAD

**Issue by xiaguangme** [scrat-team/scrat#44]
用handlebars可以用__inline预编译后调用tpl渲染模板，那用vue呢？是不是要自己定制呢？
谢谢。

**Comment by fouber** [comment]
@xiaguangme 

可以的。我们很多项目采用vue作为组件化框架。

scrat内置的配置是配了 *.handlebars 文件会经过handlebars插件的预编译处理，而vue的模板，其实是运行时在前端编译的，没有预处理的过程，所以无需配置，一般我们的vue组件是这样写的：

### 组件目录结构

```
- components
  ├─ header
  │  ├─ img
  │  ├─ header.js
  │  ├─ header.css
  │  └─ header.tpl
  ├─ ...
```

其中的 ``header.tpl`` 由于是tpl后缀，scrat中没有配置被任何工具预处理，因此可以直接借助fis的__inline方式内嵌的到其他文件中，所以我们的 ``header.js`` 通常是这样的内容：

```js
module.exports = Vue.extend({
    template: __inline('header.tpl'),
    data: function(){  // 默认数据
        return { title: '未定义标题' } 
    },
    methods: { ... }
});
```

由于__inline可以把文本文件以字符串的形式直接嵌入到js中，所以这个header.js构建之后就变成了：

```js
define('components/header/header.js', function(require, exports, module){
    module.exports = Vue.extend({
        template: '<h1>{{title}}</h1>',
        data: function(){  // 默认数据
            return { title: '未定义标题' } 
        },
        methods: { ... }
    });
});
```

然后，在其他组件中想使用这个header组件，可以这样写：

```js
// file: components/foo/foo.js

new Vue({
    el: '#main',
    template: __inline('foo.tpl'),
    components: {
        'x-header': require('header')  // 借助模块化使用组件并注册
    }
});
```

foo.tpl的模板中就能用 ``<x-header></x-header>`` 来展现组件了

**Comment by xiaguangme** [comment]
哦，template: __inline('header.tpl'),， 懂了。一开始我忽视了__inline这个函数的作用。 

这个答复一目了然，详细清晰，谢谢，十分感谢。

**Comment by fouber** [comment]
@xiaguangme 

很优雅吧

**Comment by xiaguangme** [comment]
恩恩， 赞

**Comment by ql2005** [comment]
感觉好难学啊....
scrat的 demo 太少了~~
scrat-site 的不含 vue, 好不容易 ppt 里找到个 vue-gangnam-style的,里面的结构和 scrat init 出来的完全不一样....scrat-team 里components 没有 vue, install fis-components 的么带 v,又折腾好久~按照创建生态模块的方法自己弄了个~~ fis 的 demo 里有关 vue 的又是各有各的写法..... @fouber 能推荐一个 完整一点的带 vue 的 demo 学习一下么
ps:期待scrat3

**Comment by fouber** [comment]
@ql2005 @xiaguangme 

https://github.com/idle-dog/upup

**Comment by ql2005** [comment]
THX !~ 多谢@fouber 有不明白的再来叨扰你哈~

**Comment by ql2005** [comment]
@fouber upup 不是scrat的项目吧....算了我还是自己琢磨吧 ....

**Comment by fouber** [comment]
@ql2005 

我自己随便搞的项目
