### ISSUE TITLE
scrat有没配置可以使在release的时候只release public目录[已解决，可以]

### ISSUE THREAD

**Issue by xiaguangme** [scrat-team/scrat#45]
RT。
scrat在release时 会有如下目录：
├─conf
├─private
├─public
├─server
└─views
由于一些其他原因，在release时我只需要public目录及其里面的内容，其余的目录都不要。
不知道有没有配置可以达到这个效果

**Comment by atian25** [comment]
你的场景应该是前端只输出html, 后端套模板吧? 或者是hybrid app?

有两张方法, 一种是用fis的deploy插件来过滤, 一种是自己写个shell吧

**Comment by xiaguangme** [comment]
1. 我的场景是 前端输出html js css 到静态文件服务器或者java的tomcat的应用目录下。
2. 我去试试fis的deploy插件
3. 谢谢你的答复

**Comment by xiaguangme** [comment]
在fis-conf.js中增加如下配置：
```javascript
fis.config.set('deploy', {
    tomcat : {
	    from : '/public/',
	    to : 'D:/002.tools/apache-tomcat-7.0.52/webapps/ROOT',
	    subOnly : true
	}
});
```
各配置项的意思参见[百度fis的文档](http://oak.baidu.com/fis-plus/document.html)

然后release时 用命令：
```shell
scrat release --dest tomcat
```

一开始我按百度fis的文档配置的这个不是名是local，然后不论为那个to属性怎么配置都是release到../dist，我就纳闷了，然后调试了一把，发现scrat configs目录下的default.js中有
```javascript
deploy: {
            default: {
                local: {
                    to: '../dist'
                }
           },
            compress: {
                zip: {
                }
            }
        }
```
~~

**Comment by atian25** [comment]
你可以在项目的fis-conf中覆盖掉local

**Comment by xiaguangme** [comment]
>你可以在项目的fis-conf中覆盖掉local
这个按我试验的结果看起来不行的，scrat的local配置会覆盖用户工程fis-conf中的local配置

**Comment by xiaguangme** [comment]
>你可以在项目的fis-conf中覆盖掉local


这个按我试验的结果看起来不行的，scrat的local配置会覆盖用户工程fis-conf中的local配置

**Comment by zack-lin** [comment]
@xiaguangme 其实你的需求不能用 scrat 现有的模式来实现，你应该用 fis 来定制自己的项目资源目录。scrat 现有的模式都必须依赖 node 作为 web server。

**Comment by atian25** [comment]
并不认同zack，scrat webapo模式只是定义了前端的规范，并没有约束后端。只要后端提供一个静态资源托管，还有combo服务即可。

发自我的 iPhone
