### ISSUE TITLE
scrat.js 对IE9不兼容

### ISSUE THREAD

**Issue by xiaguangme** [scrat-team/scrat#46]
proto.load 方法中：
tid = setTimeout(onerror, (options.timeout || 15) * 1000),
会报参数无效错误
我将下面的onerror函数搬到前面来声明即可解决

**Comment by fouber** [comment]
@xiaguangme

修复了这个bug，不过感觉怪怪的，按照js引擎的自行过程，进入新的作用域会立即创建var/function声明的变量，本不应该出现这个问题

**Comment by xiaguangme** [comment]
可能IE8特殊吧。  我这两正在测试scrat.js在IE8上的兼容问题， 结束后我提一个完整的影响点列表。

**Comment by fouber** [comment]
@xiaguangme 多谢支持，这部分我们确实之前没有测试过，一直以来都是应用在移动端的
