### ISSUE TITLE
fis-spriter-csssprites v0.3.4 bug

### ISSUE THREAD

**Issue by ustbhuangyi** [scrat-team/scrat#47]
![image](https://cloud.githubusercontent.com/assets/5359011/11087892/f816e882-8898-11e5-87b9-5b3572398efa.png)
这里对于file.isImage的判断有误，应该改为对item的判断

fis官方v0.3.5已修复该bug，希望scrat也升级该插件，谢谢

**Comment by atian25** [comment]
明早看看，谢谢反馈

发自我的 iPhone

**Comment by atian25** [comment]
@ustbhuangyi 已经PR, 等 @fouber 合并

**Comment by fouber** [comment]
已发布， v0.5.12
