### ISSUE TITLE
release问题

### ISSUE THREAD

**Issue by myseawp** [scrat-team/scrat#50]
@fouber 

我现在遇到一个问题：

我们这边是定制化scrat满足我们的开发要求，现在有这个需求：

执行release命令时，需要把工程的package.json编译到public目录，这样就可以直接访问127.0.0.1:5000/package.json来访问项目工程的信息了

我尝试了以下操作：

在default.js中添加配置：

            {
                reg : /^\/package.json$/i,
                release : '/public/package.json',
                useCache : false
            },
     可以正常访问，但会导致编译的www目录下没有package.json文件，执行server start命令时出错

请问下，对于这样的修改，配置该怎么写？万分感谢

**Comment by atian25** [comment]
最简单的方案，package.json还是在原位置，你的后端那里写个router就OK了

**Comment by myseawp** [comment]
我们这没有后端

只是需要从设备中直接访问调试时启动的node服务

**Comment by atian25** [comment]
node服务就是执行server目录，这就是后端

**Comment by myseawp** [comment]
ok 我试试router

**Comment by myseawp** [comment]
![1](https://cloud.githubusercontent.com/assets/13513205/11770785/1a890dce-a242-11e5-9b6a-1cb256e3190d.png)

如图：

我如果配置router话，根目录是public下面，没办法映射到上层目录啊

package.json编译到public上一级目录的

**Comment by fouber** [comment]
@myseawp 

```js
var path = require('path');
app.get('/package.json', function(req, res){
    res.sendFile(path.join(__dirname__, '../package.json'));
});
```

**Comment by myseawp** [comment]
@atian25 @fouber 

这边res.sendFile报错
我直接res.send(meta.config.test||'');

问题解决！ 感谢帮助！

**Comment by fouber** [comment]
@myseawp sendFile报错可能是路径不对吧，有没有输出一下文件路径看看？

**Comment by myseawp** [comment]
报错是：res.sendFile is not a function

但我看运行的node模块express里是有sendFile的，环境是windows 7
