### ISSUE TITLE
package.json里修改版本之后release之后define里版本不对

### ISSUE THREAD

**Issue by ql2005** [scrat-team/scrat#51]
如题...
修改版本之后页面一片空白...也没有报错
排查之后发现define里还是之前的版本号....

例如 请求到了
http://127.0.0.1:5000/c/app/2.0.0/p-index/p-index.js?_hash=41f17c7
但是响应的内容里却是
define('app/1.0.0/p-index/p-index.js'
求解...

**Comment by fouber** [comment]
是不是开启了cache？

**Comment by ql2005** [comment]
我估计是哪里 cache 的原因,但是找不到是哪个...
fis.config 的 framework.cache 这个是 localstorage 缓存,应该不是这个
在 release 的时候就出现 undefined module  app/1.0.0/boot/router.js
除此之外 fis 的 config 里没有 cache 配置了...

**Comment by ql2005** [comment]
又去研究了一下 scrat 的文档
貌似加-c, --clean参数可以解决........

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/12315249/af03b7f4-bab3-11e5-80c9-9da185ac360a.png)

检查下这个参数

**Comment by ql2005** [comment]
@atian25 如果我没理解错应该不是这个cache的原因~~ 首先我没加 -o ,应该不会生效~然后这个cache应该是localstorage 缓存?而且我去.scrat-tmp里看到文件内容也是这样的~
目前 release -wcL  加上-c之后不会出现这个问题了~

**Comment by atian25** [comment]
最好能提交个示例库

**Comment by heyfluke** [comment]
compile的cache问题。我的临时办法是 rm -rf ~/.scrat-tmp/www

**Comment by ql2005** [comment]
抱歉最近一直在赶别的项目....没有整理出demo来 =,=
@heyfluke 同学也遇到这个问题,看来不是我个例了 ^_^
-c, --clean            clean compile cache 和 rm -rf ~/.scrat-tmp/www 效果应该是一样的~
这样应该可以解决问题了~感谢 @fouber 和 @atian25 的解答!~
