### ISSUE TITLE
工程模块管理与维护

### ISSUE THREAD

**Issue by guoxmin** [scrat-team/scrat#52]
按照scrat的规范，工程模块放在components目录下，如果header组件需要改版，这时候，是新建一个组件还是在之前组件进行修改？直接修改，会影响其他页面，如果新建组件，components下的模块会不断增加，造成使用上的混乱，批量更新也是一个问题，想知道你们目前是怎样管理和维护工程模块的。

**Comment by fouber** [comment]
@guoxmin 

你的header组件改版需求，到底是希望影响其他页面还是不影响？难道改版不是希望修改一处，其他地方也生效的么？

**Comment by guoxmin** [comment]
@fouber 谢谢回答， 这个懂了。还有两个问题：1、随着项目的不断迭代，子系统下的组件会越来越多，有些可能已经没用了，你们是怎么处理的？；2、这么多组件，开展新项目的时候，你们是怎样快速找到相应组件进行复用的。

**Comment by zack-lin** [comment]
@guoxmin 

1. 没用到的组件不清理不碍事
2. UI 级别和数据级别的组件，没有什么跨项目跨业务的复用性；纯算法逻辑或者对某一 API 抽象封装的组件才有复用价值，这种情况下的组件不多，而且也会随着 npm 生态的发展而淘汰掉，维护一个内部的公共组件文档即可。

**Comment by guoxmin** [comment]
@zack-lin 也是，分治才是模块化开发最大价值
