### ISSUE TITLE
怎么把locate storage缓存关闭

### ISSUE THREAD

**Issue by jiayisheji** [scrat-team/scrat#58]
因为不能init，我把官网clone下来，安装运行，可以玩了，但是我用scrat release -LW 自动刷新，我修改文件的了，并不会自动刷新，按照注释把Cache关闭了，所有东西都从新启动了，吧浏览器locate storage的全部清除了，运行以后还是会有locate storage缓存

**Comment by xiaokaike** [comment]
在`fis-conf.js`添加如下设置

```
fis.config.set('framework', {
    cache: false,    // 关闭缓存
});
```
