### ISSUE TITLE
js声明依赖

### ISSUE THREAD

**Issue by PetersonLian** [scrat-team/scrat#61]
按照文档，是说
  >依赖的声明是按照fis的语法

我的疑问产生于scrat-site项目

该项目(scrat-site)中，**js的依赖声明**，代码里我没有找到按照`fis`的“依赖声明”的方式来声明依赖的。
例如,项目最后生成的代码里头，发现有如下的代码(依赖)
    
    "scrat-team-each/0.1.0/index.js": [
            "type"
    ],
但是，打开` "scrat-team-each/0.1.0/index.js"`的源码，
如下

    /*jshint curly: false */
    'use strict';

    var t = require('type'),
       hasOwn = Object.prototype.hasOwnProperty;

    module.exports = function (obj, iterator, context) {
      var i, l, type;
    if (typeof obj !== 'object') return;

    type = t(obj);
    context = context || obj;
    if (type === 'array' || type === 'arguments' || type === 'nodelist') {
        for (i=0, l=obj.length; i<l; i++) {
            if (iterator.call(context, obj[i], i, obj) === false) return;
        }
    } else {
        for (i in obj) {
            if (hasOwn.call(obj, i)) {
                if (iterator.call(context, obj[i], i, obj) === false) return;
            }
        }
    }
    };

我没有找到相关的js依赖声明的代码。我期望会找到

    /**
     * @require type
     */

这样的类似的代码

scrat的js的依赖声明，不是按照fis的声明依赖来的？[点击查看fis的声明依赖](https://github.com/fex-team/fis/wiki/%E5%A3%B0%E6%98%8E%E4%BE%9D%E8%B5%96#%E5%9C%A8js%E4%B8%AD%E5%A3%B0%E6%98%8E%E4%BE%9D%E8%B5%96)

**Comment by PetersonLian** [comment]
@fouber

**Comment by PetersonLian** [comment]
@xiaokaike

**Comment by atian25** [comment]
@PetersonLian 

1. `require('each')` 在这里: https://github.com/scrat-team/scrat-site/blob/master/components/menu/menu.js#L3

2. 依赖生成这里, scrat 当时做了简单的 component.json 的分析: https://github.com/scrat-team/scrat/blob/master/plugins%2Fprepackager%2Fframework-conf.js#L23

3. 现在 fis3 里面, 你可以使用 fis-hook-commonjs 这类插件即可. 当时 scrat webapp 模式刚实现的时候, fis 这块还不成熟.

**Comment by PetersonLian** [comment]
@atian25 追问。
假设我从安装了`fastclick`这个生态模块。
通过在`component.json`中的`dependencies`添加如下代码
    
    "scrat-team/fastclick": "1.0.2"
这样，我就可以下载到`fastclick`这个生态模块。
那么问题来了，当我上线的时候，我想`fastclick`采用一个cdn的地址。这怎么搞？通过`fis-conf.js`配置吗？

**Comment by atian25** [comment]
- 静态资源不应该用外链
  - 性能优化的其中一个重要的点就是减少 HTTP 请求数 
  - 一般我们会做 combo 等优化, 一旦外链就不可控了.
  - 文件也都会构建增加 md5 戳
- 做法应该是整个项目构建后的静态资源, push 到自己的 cdn 去, 通过 fis 的 domain 配置就好了.

**Comment by PetersonLian** [comment]
可否这样理解。
整个项目release出来之后，整个放到cdn上?

**Comment by atian25** [comment]
对, 根据你的部署规范去定制化 cdn 规则.

**Comment by PetersonLian** [comment]
谢
