### ISSUE TITLE
第三方js库是一个url，必须发起http请求才能返回js文件

### ISSUE THREAD

**Issue by PetersonLian** [scrat-team/scrat#64]
题目所述的情况下，是否这个第三方js库，只能做一个`<script>`标签来引用？即，只能通过外链？

**Comment by atian25** [comment]
我们不推荐使用外链, 所有的静态资源都需要放到项目中, 通过 npm / components 等方式安装到项目中.

因为只有这样, 才能完整的分析依赖, 并且处理资源合并优化等问题.
