### ISSUE TITLE
在未联网的环境下， scrat server start会hang住不动

### ISSUE THREAD

**Issue by xiaguangme** [scrat-team/scrat#65]
在未联网的环境下， scrat server start会hang住不动
调了下 发现/usr/local/lib/node_modules/scrat/node_modules/scrat-command-server index.js在start server时候会做npm install

**Comment by xiaguangme** [comment]
我暂时 把npm安装的动作去掉了 先规避了

**Comment by atian25** [comment]
不做 `npm install` 的话, 跑不起来啊, release 的那个目录里面就没有 node_modules 了.
