### ISSUE TITLE
win10  安装scrat  报错

### ISSUE THREAD

**Issue by w19871029** [scrat-team/scrat#72]
C:\Users\agan2015>npm install -g scrat
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN optional dep failed, continuing fsevents@1.0.14
|

> node-sass@3.7.0 install C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.7.0/win32-x64-14_binding.node":

connect ETIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-pngcrush@0.3.7 install C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis\node_modules\fis-optimizer-png-compressor\node_modules\node-pngcrush
> echo "Hello, World."

"Hello, World."

> images@3.0.0 install C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis\node_modules\fis-spriter-csssprites\node_modules\images
> echo "Hello, World."

"Hello, World."

> node-pngquant-native@1.0.4 install C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis\node_modules\fis-optimizer-png-compressor\node_modules\node-pngquant-native
> echo "Hello, World"

"Hello, World"

> node-sass@3.7.0 postinstall C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass
> node scripts/build.js

Building: D:\Program Files\nodejs\node.exe C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\agan2015\\AppData\\Roaming\\npm\\node_modules\\scrat\\node_modules\\fis-parser-node-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@0.12.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:90:16
     at C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:95:15)
gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:95:15)
 `which` failed  python { [Error: not found: python] code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\agan2015\\AppData\\Roaming\\npm\\node_modules\\scrat\\node_modules\\fis-parser-node-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\agan2015\AppData\Roaming\npm\node_modules\scrat\node_modules\fis-parser-node-sass\node_modules\node-sass
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\agan2015\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "scrat"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\agan2015\npm-debug.log

**Comment by atian25** [comment]
`connect ETIMEDOUT` 应该是网络问题.
