### ISSUE TITLE
requires数组为空

### ISSUE THREAD

**Issue by shunzizhan** [scrat-team/scrat#73]
最近参照 [前端开发体系建设日记](http://www.infoq.com/cn/articles/talk-front-end-integrated-solution-part2/) 研究组件化https://github.com/shunzizhan/component_demo
我用的fis3，前面的都没有什么问题，但是在文件依赖这里卡着了，文件requires数组均为空，请大神指教一下
![1](https://cloud.githubusercontent.com/assets/7811369/19381822/08ab0dd0-9230-11e6-9e60-9ac22eb5f89d.png)
![2](https://cloud.githubusercontent.com/assets/7811369/19381834/12b11fae-9230-11e6-8438-a1efb3223ca5.png)
![3](https://cloud.githubusercontent.com/assets/7811369/19381843/197a1dea-9230-11e6-96dd-9d625f269b41.png)
![4](https://cloud.githubusercontent.com/assets/7811369/19381856/22d5bc1e-9230-11e6-9eaa-b2e76bbdc91c.png)

**Comment by shunzizhan** [comment]
这么长时间了，那位大神能支援一下？

**Comment by zack-lin** [comment]
页面控制台执行 localstorage.setItem('debug', '*')，然后刷新页面，看看输出了什么 @shunzizhan

**Comment by shunzizhan** [comment]
![image](https://cloud.githubusercontent.com/assets/7811369/19672716/91b2bd16-9aab-11e6-857c-d6a88e27c30f.png)
报错了

**Comment by zack-lin** [comment]
大小写拼错了 localStorage.setItem('debug', '*')

**Comment by shunzizhan** [comment]
啥都没有

**Comment by zack-lin** [comment]
@shunzizhan 没刷新页面肯定啥都没有嘛

**Comment by shunzizhan** [comment]
页面控制台执行 localStorage.setItem('debug', '*')，然后手动刷新页面，页面控制台执行 localStorage.getItem('debug', '*')

**Comment by zack-lin** [comment]
@shunzizhan 你非要这么理解的话，我真帮不到你什么了。

**Comment by zack-lin** [comment]
我看了下你截图的错误日志，__FRAMWORK_CONFIG__ 没用被替换掉，再仔细理解下 scrat 的代码吧

**Comment by shunzizhan** [comment]
行吧，或许是我那个环节不对吧，实在不行，只能另想出路了

**Comment by atian25** [comment]
@mansonchor 你看下 quickstart 的启动方式, 我怀疑你没有用 scrat release 和 start, 所以才没有被替换掉. 你是直接在 IDE 里面点击 preview 的么?

**Comment by shunzizhan** [comment]
我的项目是基于fis3的，没有完成用松鼠团队的模板，参照那个 （前端开发体系建设日记）[http://www.infoq.com/cn/articles/talk-front-end-integrated-solution-part2/]，到文件依赖，看到scrat.js，在项目里引入了这个js而已 @atian25

**Comment by shunzizhan** [comment]
我的项目是基于fis3的，没有完成用松鼠团队的模板，参照那个 （前端开发体系建设日记）[http://www.infoq.com/cn/articles/talk-front-end-integrated-solution-part2/]，到文件依赖，看到scrat.js，在项目里引入了这个js而已 @atian25

**Comment by atian25** [comment]
.... scrat.js 是要配合 scrat 用的... 用 fis3 肯定不行....

https://github.com/scrat-team/scrat/blob/master/plugins/prepackager/framework-conf.js#L173

**Comment by shunzizhan** [comment]
好吧，我以为这个封装的想jq一样，谢谢@atian25
