### ISSUE TITLE
Linux 平台无法运行

### ISSUE THREAD

**Issue by geekdada** [scrat-team/scrat#75]
运行报错

```bash
/usr/bin/env: 'node\r': No such file or directory
```

`bin/scrat` 里出现了 `\r`

**Comment by atian25** [comment]
... 自己 PR... 然后你不是用内部的 scrat3 么?

**Comment by geekdada** [comment]
老项目还要维护
马上提

李一航 Roy Li
On Thu, Jun 15, 2017 at 3:12 PM, TZ | 天猪 <notifications@github.com> wrote:
... 自己 PR... 然后你不是用内部的 scrat3 么?

**Comment by geekdada** [comment]
npm 里的文件是有问题的，github 里的是没问题的

**Comment by atian25** [comment]
重新发布一个 patch

**Comment by geekdada** [comment]
Fixed in 0.10.0
