### ISSUE TITLE
安装 yyx990803/vue 出现一溜警告~ 

### ISSUE THREAD

**Issue by qdsang** [scrat-team/scrat#8]
![image](https://cloud.githubusercontent.com/assets/804455/3965854/bdb8f41e-279b-11e4-9a25-b524229e9d1d.png)
打开方式不对么？

**Comment by okoala** [comment]
问题应该是模块无法自动识别 require('./utils/index') 为 require('./utils') 所以疯狂报错。在vue源码中批量改成前一种就可以了。话说基于component的生态确实不太稳定，期待新的方案~~
